from enum import Enum
from collections import namedtuple

#CDH
OP_CDH_GET_CONNECTED_DEVICES = 0xc0
OP_CDH_CONNECT_DEVICE = 0xc1

#FCM
OP_FCM_VALVES_SET_ALL   = 0x30
OP_FCM_VALVES_GET_ALL   = 0x31
OP_FCM_PRESS_VENT_SET   = 0x32
OP_FCM_PRESS_VENT_DELAY = 0x33
OP_FCM_OX_VENT_SET      = 0x34
OP_FCM_OX_VENT_DELAY    = 0x35
OP_FCM_FUEL_VENT_SET    = 0x36
OP_FCM_FUEL_VENT_DELAY  = 0x37
OP_FCM_FUEL_CC_SET      = 0x38
OP_FCM_FUEL_CC_DELAY    = 0x39
OP_FCM_OX_CC_SET        = 0x3a
OP_FCM_OX_CC_DELAY      = 0x3b
OP_FCM_OX_DUMP_SET      = 0x3c
OP_FCM_OX_DUMP_DELAY    = 0x3d

#GCM
OP_GCM_IGNITION_SET     = 0x40
OP_GCM_QD_SET           = 0x41
OP_GCM_KBTL_FILL_SET    = 0x42
OP_GCM_TBTL_FILL_SET    = 0x43

class OpType(Enum):
    SETVALVE = 1
    SETBULK = 2
    SETDELAYED = 3

OPCODE_TYPES = {
    OP_FCM_PRESS_VENT_DELAY:    OpType.SETDELAYED,
    OP_FCM_OX_VENT_DELAY:       OpType.SETDELAYED,
    OP_FCM_FUEL_VENT_DELAY:     OpType.SETDELAYED,
    OP_FCM_FUEL_CC_DELAY:       OpType.SETDELAYED,
    OP_FCM_OX_CC_DELAY:         OpType.SETDELAYED,
    OP_FCM_OX_DUMP_DELAY:       OpType.SETDELAYED,

    OP_FCM_VALVES_SET_ALL:      OpType.SETBULK,
    OP_FCM_VALVES_GET_ALL:      OpType.SETBULK,

    OP_GCM_IGNITION_SET:        OpType.SETVALVE,
    OP_GCM_QD_SET:              OpType.SETVALVE,
    OP_GCM_KBTL_FILL_SET:       OpType.SETVALVE,
    OP_GCM_TBTL_FILL_SET:       OpType.SETVALVE,

    OP_FCM_PRESS_VENT_SET:      OpType.SETVALVE,
    OP_FCM_OX_VENT_SET:         OpType.SETVALVE,
    OP_FCM_FUEL_VENT_SET:       OpType.SETVALVE,
    OP_FCM_FUEL_CC_SET:         OpType.SETVALVE,
    OP_FCM_OX_CC_SET:           OpType.SETVALVE,
    OP_FCM_OX_DUMP_SET:         OpType.SETVALVE
}

OPCODE_STRINGS = {
    #CDH
    OP_CDH_GET_CONNECTED_DEVICES:   "CDH_GET_CONNECTED_DEVICES",
    OP_CDH_CONNECT_DEVICE:          "CDH_CONNECT_DEVICE",

    #FCM
    OP_FCM_VALVES_SET_ALL:      "FCM_VALVES_SET_ALL",
    OP_FCM_VALVES_GET_ALL:      "FCM_VALVES_GET_ALL",
    OP_FCM_PRESS_VENT_SET:      "FCM_PRESS_VENT_SET",
    OP_FCM_PRESS_VENT_DELAY:    "FCM_PRESS_VENT_DELAY",
    OP_FCM_OX_VENT_SET:         "FCM_OX_VENT_SET",
    OP_FCM_OX_VENT_DELAY:       "FCM_OX_VENT_DELAY",
    OP_FCM_FUEL_VENT_SET:       "FCM_FUEL_VENT_SET",
    OP_FCM_FUEL_VENT_DELAY:     "FCM_FUEL_VENT_DELAY",
    OP_FCM_FUEL_CC_SET:         "FCM_FUEL_CC_SET",
    OP_FCM_FUEL_CC_DELAY:       "FCM_FUEL_CC_DELAY",
    OP_FCM_OX_CC_SET:           "FCM_OX_CC_SET",
    OP_FCM_OX_CC_DELAY:         "FCM_OX_CC_DELAY",
    OP_FCM_OX_DUMP_SET:         "FCM_OX_DUMP_SET",
    OP_FCM_OX_DUMP_DELAY:       "FCM_OX_DUMP_DELAY",

    #GCM
    OP_GCM_IGNITION_SET:        "GCM_IGNITION_SET",
    OP_GCM_QD_SET:              "GCM_QD_SET",
    OP_GCM_KBTL_FILL_SET:       "GCM_KBTL_FILL_SET",
    OP_GCM_TBTL_FILL_SET:       "GCM_TBTL_FILL_SET"
}
