from enum import Enum
from collections import namedtuple

#CDH
GET_CONNECTED_DEVICES = 0xc0
CONNECT_DEVICE = 0xc1

#FCM
VALVES_SET_ALL = 0x30
VALVES_GET_ALL = 0x31

PRESS_PROP_SET = 0x32
OX_FILL_SET = 0x33
PRESS_VENT_SET = 0x34
PRESS_VENT_DELAYED_SET = 0x35
OX_VENT_SET = 0x36
OX_VENT_DELAYED_SET = 0x37
FUEL_VENT_SET = 0x38
FUEL_VENT_DELAYED_SET = 0x39
FUEL_CC_SET = 0x3a
FUEL_CC_DELAYED_SET =0x3b
OX_CC_SET = 0x3c
OX_CC_DELAYED_SET = 0x3d
OX_DUMP_SET = 0x3e

#GCM
PRESS_FILL_SET = 0x40
IGNITION_SET = 0x41
#IGNITE_FOR_TIME = 0x42
QD_SET = 0x43
#QD_CHECK_READY = 0x44

class OpType(Enum):
    SETVALVE = 1
    SETBULK = 2
    SETDELAYED = 3

OPCODE_TYPES = {
    PRESS_VENT_DELAYED_SET: OpType.SETDELAYED,
    OX_VENT_DELAYED_SET: OpType.SETDELAYED,
    FUEL_VENT_DELAYED_SET: OpType.SETDELAYED,
    FUEL_CC_DELAYED_SET: OpType.SETDELAYED,
    OX_CC_DELAYED_SET: OpType.SETDELAYED,

    VALVES_SET_ALL: OpType.SETBULK,
    VALVES_GET_ALL: OpType.SETBULK,

    QD_SET: OpType.SETVALVE,
    PRESS_PROP_SET: OpType.SETVALVE,
    OX_FILL_SET: OpType.SETVALVE,
    PRESS_VENT_SET: OpType.SETVALVE,
    OX_VENT_SET: OpType.SETVALVE,
    FUEL_VENT_SET: OpType.SETVALVE,
    FUEL_CC_SET: OpType.SETVALVE,
    OX_CC_SET: OpType.SETVALVE,
    PRESS_FILL_SET: OpType.SETVALVE,
    IGNITION_SET: OpType.SETVALVE,
    OX_DUMP_SET: OpType.SETVALVE
}
